---
title: "GF-0604 Procesamiento<br>de datos geográficos<br><br>Markdown y R Markdown"
author: "Manuel Vargas"
date: "2020-03-12"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Markdown

- [Markdown](https://daringfireball.net/) es un [lenguaje de marcas](https://en.wikipedia.org/wiki/Markup_language) creado en 2004 por John Gruber. **NOTA**: las **marcas** se utilizan para brindar información acerca de la presentación (ej. negritas, itálicas) o la estructura (ej. títulos, encabezados) de un documento.
- Markdown se caracteriza por ser más sencillo de leer y de usar que otros lenguajes de marcas (ej. [HTML](https://en.wikipedia.org/wiki/HTML)).
- Los documentos escritos en Markdown pueden exportarse a una gran variedad de formatos (ej. HTML, Doc, PDF, Latex) para ser usados en libros, presentaciones o páginas web, entre otros.
- Markdown es ampliamente utilizado en comunicación científica, documentación de programas e investigación reproducible.

## Variaciones de Markdown
También llamadas _flavors_, son extensiones o modificaciones de la especificación original de Markdown. Entre las más populares están:

- [R Markdown](): para el lenguaje R.
- [GitHub Flavored Markdown](https://help.github.com/en/github/writing-on-github): para el sitio GitHub.
- [Python Markdown](): para el lenguaje Python.
- [Pandoc's Markdown](): para el programa [Pandoc](https://pandoc.org/) de conversión entre formatos.
- [Kramdown](https://kramdown.gettalong.org/quickref.html): para el lenguaje Ruby.

Puede verse una lista más extensa en [https://github.com/commonmark/commonmark-spec/wiki/markdown-flavors](https://github.com/commonmark/commonmark-spec/wiki/markdown-flavors).

## R Markdown

## Recursos sobre Markdown y R Markdown

- Sitio oficial de Markdown: [Daring Fireball: Markdown](https://daringfireball.net/projects/markdown/)
- Página en Wikipedia sobre Markdown: [Markdown - Wikipedia](https://en.wikipedia.org/wiki/Markdown)
- Guía de referencia de Markdown: [Markdown Guide](https://www.markdownguide.org/)
- Ficha de ayuda de GitHub Markdown: [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- Tutorial sobre Markdown: [Markdown Tutorial](https://www.markdowntutorial.com/)

- Sitio oficial de R Markdown: [R Markdown](https://rmarkdown.rstudio.com/)
- Libro sobre R Markdown: [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
- Guía de referencia de R Markdown: [R Markdown Reference](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)
- Ficha de ayuda de R Markdown: [R Markdown Cheat Sheet](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)